// <auto-generated />
using Etteplan_XmlFile_MVC_DB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Etteplan_XmlFile_MVC_DB.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230802153457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Etteplan_XmlFile_MVC_DB.Models.TransUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransUnits");

                    b.HasData(
                        new
                        {
                            Id = 42006,
                            Source = "WARNING",
                            Target = "VARNING"
                        },
                        new
                        {
                            Id = 42007,
                            Source = "Note",
                            Target = "Obs!"
                        },
                        new
                        {
                            Id = 42008,
                            Source = "DANGER",
                            Target = "FARA"
                        },
                        new
                        {
                            Id = 42009,
                            Source = "CAUTION",
                            Target = "FÖRSIKTIGHET"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
